name: Sync OAS to ReadMe
on:
  push:
    branches:
      - prod
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: GitHub Action
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload yaml-unresolved/openapi.yaml --key=${{ secrets.README_API_KEY }} }}
